package config

import (
	"os"
	"os/exec"
	"strings"
	"text/template"
)

// Env reads an environment variable with a default.
func Env(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// ServiceHealth checks if a process is running.
type ServiceStatus struct {
	Name    string `json:"name"`
	Running bool   `json:"running"`
}

// CheckServices returns health status of Mailpit, Postfix, OpenDKIM.
func CheckServices() []ServiceStatus {
	return []ServiceStatus{
		{Name: "Mailpit", Running: processRunning("mailpit")},
		{Name: "Postfix", Running: postfixRunning()},
		{Name: "OpenDKIM", Running: processRunning("opendkim")},
	}
}

func processRunning(name string) bool {
	// Use pidof (busybox) instead of pgrep (not on Alpine by default)
	out, err := exec.Command("pidof", name).Output()
	return err == nil && len(strings.TrimSpace(string(out))) > 0
}

func postfixRunning() bool {
	// Check for master process directly
	return processRunning("master")
}

// ApplySettings writes settings to Postfix/OpenDKIM config files and reloads.
// This is called from the settings handler after updating the DB.
func ApplySettings(settings map[string]string) error {
	mailMode := settings["mail_mode"]
	if mailMode == "" {
		mailMode = "catch"
	}

	if mailMode == "catch" {
		return nil // Nothing to configure
	}

	// Generate main.cf
	return generateMainCf(settings)
}

func generateMainCf(s map[string]string) error {
	tmpl := `# Generated by Pilot UI — do not edit manually.
myhostname = {{.postfix_hostname}}
myorigin   = {{.postfix_myorigin}}
mydestination      = localhost, $myhostname
mynetworks         = {{or .postfix_mynetworks "127.0.0.0/8"}}
inet_interfaces    = loopback-only
inet_protocols     = ipv4
message_size_limit = {{or .postfix_message_size "52428800"}}
queue_directory   = /var/spool/postfix
command_directory = /usr/sbin
daemon_directory  = /usr/libexec/postfix
data_directory    = /var/lib/postfix
mail_owner        = postfix
compatibility_level = 3.6
maillog_file = /dev/stdout
disable_vrfy_command    = yes
smtpd_helo_required     = yes
strict_rfc821_envelopes = yes
smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination
`

	t, err := template.New("main.cf").Funcs(template.FuncMap{
		"or": func(a, b string) string {
			if a != "" {
				return a
			}
			return b
		},
	}).Parse(tmpl)
	if err != nil {
		return err
	}

	f, err := os.Create("/etc/postfix/main.cf")
	if err != nil {
		return err
	}
	defer f.Close()

	if err := t.Execute(f, s); err != nil {
		return err
	}

	// Reload postfix
	_ = exec.Command("postfix", "reload").Run()
	return nil
}
